# Use the official Python image from the Docker Hub
FROM python:3.11.3-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy project
COPY . /app/

# Collect static files


# Expose port 8000
EXPOSE 8000

# Run the application
CMD ["gunicorn", "website.wsgi:application", "--bind", "0.0.0.0:8000"]
