# Generated by Django 5.0.1 on 2024-02-28 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_quote_order_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='user',
        ),
        migrations.AddField(
            model_name='homeowner',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.userprofile'),
        ),
        migrations.AddField(
            model_name='professional',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.userprofile'),
        ),
    ]
