# Generated by Django 5.0.1 on 2024-03-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_professional_previous_work_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
