# Generated by Django 5.0.1 on 2024-03-05 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homeowner_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='professional_photos/'),
        ),
        migrations.AddField(
            model_name='professional',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to='home.userprofile'),
        ),
    ]
