# Generated by Django 5.0.1 on 2024-03-12 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_previouswork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homeowner')),
                ('previous_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.previouswork')),
            ],
        ),
    ]
