# Generated by Django 5.0.1 on 2024-03-13 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='previous_work',
        ),
        migrations.AlterField(
            model_name='previouswork',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='home.professional'),
        ),
    ]
