# Generated by Django 5.0.1 on 2024-03-14 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_professional_previous_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='previous_work',
            field=models.FileField(blank=True, null=True, upload_to='previous_work/'),
        ),
        migrations.AlterField(
            model_name='previouswork',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.professional'),
        ),
    ]
