# Generated by Django 5.0.1 on 2024-03-14 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_previousworkimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousworkimage',
            name='previous_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.previouswork'),
        ),
    ]
