# Generated by Django 5.0.1 on 2024-03-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_previousworkimage_previous_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previouswork',
            name='image',
        ),
    ]
