# Generated by Django 5.0.1 on 2024-03-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_projectimage_delete_previousworkimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='previouswork',
            name='products_used',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='previouswork',
            name='project_name',
            field=models.CharField(max_length=100),
        ),
    ]
