# Generated by Django 5.0.1 on 2024-03-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_projectimage_professional_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='professional_name',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='professional_profile_link',
        ),
    ]
