# Generated by Django 4.2.7 on 2024-04-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_professional_previous_work_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeowner',
            name='wishlist_items',
            field=models.ManyToManyField(blank=True, related_name='homeowners', to='home.previouswork'),
        ),
    ]
