# Generated by Django 5.0.1 on 2024-04-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_professional_previous_work_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
