# Generated by Django 5.0.1 on 2024-04-05 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_homeowner_wishlist_items'),
        ('home', '0025_professional_rating'),
    ]

    operations = [
    ]
