# Generated by Django 5.0.1 on 2024-04-05 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_merge_20240406_0155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeowner',
            name='wishlist_items',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='rating',
        ),
        migrations.AddField(
            model_name='professional',
            name='cumulative_rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professional',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.professional')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('professional', 'user')},
            },
        ),
    ]
