# Generated by Django 5.0.1 on 2024-04-27 14:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 27, 17, 18, 52, 326202)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='homeowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='home.homeowner'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='في الانتظار', max_length=20),
        ),
    ]
