# Generated by Django 5.0.1 on 2024-04-28 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_order_created_at_alter_order_homeowner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='terms',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='cost',
            new_name='price',
        ),
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('pending', 'في الانتظار'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
