# Generated by Django 5.0.1 on 2024-04-29 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_rename_terms_quote_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='price',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='description',
            new_name='terms',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='status',
        ),
        migrations.AlterField(
            model_name='quote',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.order'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.professional'),
        ),
    ]
