# Generated by Django 5.0.1 on 2024-04-29 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_rename_price_quote_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 29, 5, 15, 51, 326054)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(default='في الانتظار', max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
